spring:
  cloud:
    openfeign:
      client:
        config:
          default: # 默认的服务用到 feign 的配置 【超时设置】
            logger-level: full
            connect-timeout: 2000 # 默认10 * 1000 毫秒
            read-timeout: 3000 # 默认 60 * 1000 ms

          service-product: # 具体服务名
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.codebest.order.interceptor.XTokenRequestInterceptor  # 仅对客户端有效的拦截器，或者直接在这类上加 @component cloud能所有请求都自动识别的，并调用到拦截器
feign:
  sentinel:
    enabled: true  # 这个功能开启，远程调用失败就会 走它兜底方法
